[package]
name = "dyphengine"
version = "0.1.0"
edition = "2018"

[dependencies]
console = {path = "../console"}
parser = {path = "../parser"}
file_manager = {path = "../file_manager"}
structopt = "0.3.13"